version: '3.9' # Use the latest version or compatible one

services:
  postgres:
    image: postgres:latest
    container_name: socialscores-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234
      POSTGRES_DB: socialscores
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
